seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed  # Caveat: fp16 doesn't work with pretrained T5. See https://github.com/huggingface/transformers/issues/10830
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
  gradient_clip_val: 1.0
  max_steps: 500000
  accumulate_grad_batches: 1
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_last: true
        save_top_k: 1
        monitor: Recall@10_val
        auto_insert_metric_name: true
        mode: max
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: Recall@10_val
        patience: 3
        mode: max
        verbose: true

model:
  model_name: google/byt5-small  # Can be larger
  lr: 1e-4
  warmup_steps: 2000
  num_retrieved: 100

data:
  data_path: data/lean_bench/random/
  corpus_path: data/lean_bench/corpus.jsonl
  num_negatives: 3
  num_in_file_negatives: 1
  accessible_premises_only: true
  batch_size: 8
  eval_batch_size: 128
  max_seq_len: 1024  # Can be larger.
  num_workers: 8

