seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16  # Caveat: fp16 doesn't work with pretrained T5. See https://github.com/huggingface/transformers/issues/10830
  strategy: deepspeed_stage_2
  gradient_clip_val: 1.0
  max_epochs: 10
  accumulate_grad_batches: 4
  # check_val_every_n_epoch: 4
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    # - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    #  init_args:
    #    verbose: true
    #    save_last: true
    #    save_top_k: 1
    #    monitor: Overall_val
    #    auto_insert_metric_name: true
    #    mode: max
    # - class_path: pytorch_lightning.callbacks.EarlyStopping
    #  init_args:
    #    monitor: val_top5_acc
    #    patience: 2
    #    mode: max
    #    verbose: true

model:
  model_name: google/byt5-small
  lr: 1e-4
  warmup_steps: 2000
  dual_encoder: false

data:
  data_path: data/lean_bench/random/
  corpus_path: data/lean_bench/corpus.jsonl
  num_negatives: 3
  batch_size: 8  # effective_batch_size == batch_size * accumulate_grad_batches * devices
  max_seq_len: 1024  # A little bit too small.
  num_workers: 8